server:
  port: 8189
  servlet:
    context-path: /library
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=muctr
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#  postgres:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
  flyway:
    user: postgres
    password: admin
    schema: muctr
    baselineOnMigrate: true
